/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  CxipProvenanceProxy,
  CxipProvenanceProxyInterface,
} from "../CxipProvenanceProxy";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060f68061001f6000396000f3fe6080604081905263e60acf2960e01b815260009073dfbb74177c45c82ac06327c204bb5ef2daec57b89063e60acf2990608490602090600481865afa158015604b573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190606d91906092565b90503660008037600080366000845af43d6000803e808015608d573d6000f35b3d6000fd5b60006020828403121560a357600080fd5b81516001600160a01b038116811460b957600080fd5b939250505056fea2646970667358221220eab3acfaa332a40c858b156c874661e56aa4f099cf4b3e1e74b22941b4859cc464736f6c634300080c0033";

type CxipProvenanceProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CxipProvenanceProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CxipProvenanceProxy__factory extends ContractFactory {
  constructor(...args: CxipProvenanceProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "CxipProvenanceProxy";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CxipProvenanceProxy> {
    return super.deploy(overrides || {}) as Promise<CxipProvenanceProxy>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CxipProvenanceProxy {
    return super.attach(address) as CxipProvenanceProxy;
  }
  connect(signer: Signer): CxipProvenanceProxy__factory {
    return super.connect(signer) as CxipProvenanceProxy__factory;
  }
  static readonly contractName: "CxipProvenanceProxy";
  public readonly contractName: "CxipProvenanceProxy";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CxipProvenanceProxyInterface {
    return new utils.Interface(_abi) as CxipProvenanceProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CxipProvenanceProxy {
    return new Contract(address, _abi, signerOrProvider) as CxipProvenanceProxy;
  }
}
