/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  CxipERC721Proxy,
  CxipERC721ProxyInterface,
} from "../CxipERC721Proxy";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060f68061001f6000396000f3fe60806040819052632c5feccb60e11b815260009073dfbb74177c45c82ac06327c204bb5ef2daec57b8906358bfd99690608490602090600481865afa158015604b573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190606d91906092565b90503660008037600080366000845af43d6000803e808015608d573d6000f35b3d6000fd5b60006020828403121560a357600080fd5b81516001600160a01b038116811460b957600080fd5b939250505056fea2646970667358221220ad199d1f1082271d68a8b4f853989c2d103d3ff654c403949500b331f759051e64736f6c634300080c0033";

type CxipERC721ProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CxipERC721ProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CxipERC721Proxy__factory extends ContractFactory {
  constructor(...args: CxipERC721ProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "CxipERC721Proxy";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CxipERC721Proxy> {
    return super.deploy(overrides || {}) as Promise<CxipERC721Proxy>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CxipERC721Proxy {
    return super.attach(address) as CxipERC721Proxy;
  }
  connect(signer: Signer): CxipERC721Proxy__factory {
    return super.connect(signer) as CxipERC721Proxy__factory;
  }
  static readonly contractName: "CxipERC721Proxy";
  public readonly contractName: "CxipERC721Proxy";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CxipERC721ProxyInterface {
    return new utils.Interface(_abi) as CxipERC721ProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CxipERC721Proxy {
    return new Contract(address, _abi, signerOrProvider) as CxipERC721Proxy;
  }
}
