/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  CxipIdentityProxy,
  CxipIdentityProxyInterface,
} from "../CxipIdentityProxy";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060f68061001f6000396000f3fe6080604081905263071b938d60e31b815260009073e7f1725e7734ce288f8367e1bb143e90bb3f0512906338dc9c6890608490602090600481865afa158015604b573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190606d91906092565b90503660008037600080366000845af43d6000803e808015608d573d6000f35b3d6000fd5b60006020828403121560a357600080fd5b81516001600160a01b038116811460b957600080fd5b939250505056fea26469706673582212208946e1a7de585e83ddba36332acc62598a9d62e903d96e35157330f329e2f70d64736f6c634300080c0033";

type CxipIdentityProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CxipIdentityProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CxipIdentityProxy__factory extends ContractFactory {
  constructor(...args: CxipIdentityProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "CxipIdentityProxy";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CxipIdentityProxy> {
    return super.deploy(overrides || {}) as Promise<CxipIdentityProxy>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CxipIdentityProxy {
    return super.attach(address) as CxipIdentityProxy;
  }
  connect(signer: Signer): CxipIdentityProxy__factory {
    return super.connect(signer) as CxipIdentityProxy__factory;
  }
  static readonly contractName: "CxipIdentityProxy";
  public readonly contractName: "CxipIdentityProxy";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CxipIdentityProxyInterface {
    return new utils.Interface(_abi) as CxipIdentityProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CxipIdentityProxy {
    return new Contract(address, _abi, signerOrProvider) as CxipIdentityProxy;
  }
}
