/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  CxipAssetProxy,
  CxipAssetProxyInterface,
} from "../CxipAssetProxy";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060f68061001f6000396000f3fe608060408190526331e2186d60e11b815260009073e7f1725e7734ce288f8367e1bb143e90bb3f0512906363c430da90608490602090600481865afa158015604b573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190606d91906092565b90503660008037600080366000845af43d6000803e808015608d573d6000f35b3d6000fd5b60006020828403121560a357600080fd5b81516001600160a01b038116811460b957600080fd5b939250505056fea2646970667358221220031ef6df6f0cd39288862209f897c8d2421e69457146936f9121fe3b49722bb764736f6c634300080c0033";

type CxipAssetProxyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CxipAssetProxyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CxipAssetProxy__factory extends ContractFactory {
  constructor(...args: CxipAssetProxyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "CxipAssetProxy";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CxipAssetProxy> {
    return super.deploy(overrides || {}) as Promise<CxipAssetProxy>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CxipAssetProxy {
    return super.attach(address) as CxipAssetProxy;
  }
  connect(signer: Signer): CxipAssetProxy__factory {
    return super.connect(signer) as CxipAssetProxy__factory;
  }
  static readonly contractName: "CxipAssetProxy";
  public readonly contractName: "CxipAssetProxy";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CxipAssetProxyInterface {
    return new utils.Interface(_abi) as CxipAssetProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CxipAssetProxy {
    return new Contract(address, _abi, signerOrProvider) as CxipAssetProxy;
  }
}
