/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RaribleRoyaltiesInterface extends utils.Interface {
  contractName: "RaribleRoyalties";
  functions: {
    "owner()": FunctionFragment;
    "royaltiesProviders(address)": FunctionFragment;
    "setProviderByToken(address,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "royaltiesProviders",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setProviderByToken",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "royaltiesProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProviderByToken",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RaribleRoyalties extends BaseContract {
  contractName: "RaribleRoyalties";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RaribleRoyaltiesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    owner(overrides?: CallOverrides): Promise<[string]>;

    royaltiesProviders(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setProviderByToken(
      token: string,
      provider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  owner(overrides?: CallOverrides): Promise<string>;

  royaltiesProviders(arg0: string, overrides?: CallOverrides): Promise<string>;

  setProviderByToken(
    token: string,
    provider: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    owner(overrides?: CallOverrides): Promise<string>;

    royaltiesProviders(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    setProviderByToken(
      token: string,
      provider: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    royaltiesProviders(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setProviderByToken(
      token: string,
      provider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    royaltiesProviders(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setProviderByToken(
      token: string,
      provider: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
